# Generated by Django 3.2.5 on 2021-07-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_auto_20210710_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(default='dk', max_length=3),
        ),
    ]
